### ISSUE TITLE
README.md内で参照しているHPのリンク切れ

### ISSUE THREAD

**Issue by rkarsnk** [tkmc/486#13]
README.mdで参照している以下のURLリンクはリンクが古くなっており、自動的にKADOKAWAのサイトに遷移します。

リンク切れのサイト：
```
http://ascii.asciimw.jp/books/books/detail/4-7561-0213-1.shtml
```

角川のサイトであれば、以下のURLが電子版「はじめて読む486」のリンクになります。
```
https://www.kadokawa.co.jp/product/200600002422/
```

**Comment by tkmc** [comment]
ご指摘ありがとうございます。
修正しました。
